# Centos 7 specific
- name: Start monit
  shell: systemctl start monit.service
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")
  
- name: Reload monit definitions
  shell: monit reload

- name: Stop all services
  shell: monit stop all
  register: result
  until: result.rc == 0
  retries: 20
  delay: 10

- name: Find the services installed on the host
  shell: monit summary | tail -n +3 | awk -F"'" '{print $2}'
  register: installed_services

# which services that need started are actually installed on this host?
- set_fact:
    installed_services_to_start: "{{ services_to_start | intersect(installed_services.stdout_lines) }}"

- name: Start services
  debug:
    msg: "Attemping to start: {{ installed_services_to_start }}"

- name: Wait for services to start
  shell: "monit start {{ item }}"
  with_items: "{{ installed_services_to_start }}"
  register: result
  until: result.rc == 0
  retries: 20
  delay: 10
