- name: Get epel-repo rpm
  get_url:
    dest: /tmp/epel-release.rpm
    url: http://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm

- name: Install epel-repo rpm
  yum:
    pkg: /tmp/epel-release.rpm
    state: installed
  register: result
  until: result.rc == 0
  retries: 5
  delay: 10
