- name: Install monit
  yum:
    name: monit
  register: result
  until: result.rc == 0
  retries: 5
  delay: 10

- name: Deploy monit configuration
  template: src=monitrc dest=/etc/monitrc mode=0600