- name: Create monit home
  file: path={{ monit_home }} state=directory mode=0755

#
# Centos 7 specific
#
- name: Create monit centos 7 definition for elasticsearch
  template: src=elasticsearch.monit dest={{ monit_config_home }}/elasticsearch.monit
  when: ("search" in group_names) and (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")