- name: Start Elasticsearch
  service: name=elasticsearch state=started

- name : Wait for Elasticsearch Host to Start
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: "{{ elasticsearch_web_port }}"
    delay: 10
    timeout: 300
  when: ("{{elasticsearch_network_interface}}" != 'local')

- name: Wait for Index to Become Available
  uri:
    url: "http://{{ ansible_default_ipv4.address }}:{{ elasticsearch_web_port }}/_cat/health"
    method: GET
    status_code: 200
    return_content: yes
  register: result
  until: result.content.find("green") != -1 or result.content.find("yellow") != -1
  retries: 10
  delay: 60
  when: ("{{elasticsearch_network_interface}}" != 'local')