- name: Download Nodesource Yum Repository Setup
  shell: wget -O /tmp/nodesource_setup_4.x {{ nodesource_repo_setup }} 
  # get_url: url={{ nodesource_repo_setup }} dest=/tmp/nodesource_setup_4.x

- name: Setup Nodesource Yum Repository
  shell: bash /tmp/nodesource_setup_4.x

- name: Install Node - Needed for Elasticdump
  yum: name="{{ item }}"
  with_items:
    - gcc-c++
    - make
    - nodejs

- name: Install Elasticdump
  shell: npm install elasticdump -g
