- name: Check for elasticsearch bin at "{{ elasticsearch_bin_path }}"
  stat: path="{{ elasticsearch_bin_path }}"
  register: es_bin_path
  
- name: Check for head plugin at "{{ elasticsearch_plugin_path }}/head"
  stat: path="{{ elasticsearch_plugin_path }}/head"
  register: head_plugin_path
  
- name: Install head-plugin as es plugin
  command: "{{ elasticsearch_bin_path }}/plugin install mobz/elasticsearch-head"
  when: (es_bin_path.stat.exists == True) and (head_plugin_path.stat.exists == False)