- name: Check OS Version
  fail: msg="elasticsearch-deployments supports currently CentOS 7 only."
  when: (ansible_distribution != "CentOS" or ansible_distribution_major_version != "7")

- name: Ensure firewalld is stopped and is not running at boot time.
  shell: systemctl stop firewalld && systemctl disable firewalld
  when: (ansible_distribution == "CentOS" and ansible_distribution_major_version == "7")

- name: Remove ipv4 'localhost.localdomain' from /etc/hosts
  lineinfile: dest=/etc/hosts state=absent regexp="^127.0.0.1(.*)localdomain(.*)$"

- name: Remove ipv6 'localhost.localdomain' from /etc/hosts
  lineinfile: dest=/etc/hosts state=absent regexp="^::1(.*)localdomain(.*)$"

- name: Add localhost to /etc/hosts
  lineinfile: dest=/etc/hosts line="127.0.0.1   localhost"

- name: Remove hostname and ip to /etc/hosts if already exist
  lineinfile: dest=/etc/hosts state=absent regexp="^{{ ansible_default_ipv4.address }}   node-{{ ansible_default_ipv4.address.replace('.','') }}"

- name: Add hostname and ip to /etc/hosts
  lineinfile: dest=/etc/hosts line="{{ ansible_default_ipv4.address }}   node-{{ ansible_default_ipv4.address.replace('.','') }}"