#
# prerequisites
#
- hosts: search
  become: true
  roles:
    - role: common
  tags:
    - common

#
# search
#
- hosts: search_master, search_data
  become: true
  vars:
    es_hosts: "{% set comma = joiner(',') %}{% for host in groups['search'] -%}{{ comma() }}{{ host }}{%- endfor %}"
  roles:
    - role: elasticsearch
    - { role: elasticsearch_init, tags: ['elasticsearch_init'] }
  tags:
    - elasticsearch
    
#
# elasticdump
#
- hosts: search
  become: true
  roles:
    - role: elasticdump
  tags:
    - elasticdump
    
#
# head-plugin
#
- hosts: search
  become: true
  roles:
    - role: head-plugin
  tags:
    - head-plugin
    
#
# monit
#
- hosts: search
  become: true
  roles:
    - role: monit
  tags:
    - monit
    
- hosts: search
  become: true
  roles:
    - role: monit-start
  tags:
    - monit-start    